# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_book_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(related_name='reviews', to='belt_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
