# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_auto_20180102_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='God', max_length=255),
            preserve_default=False,
        ),
    ]
