# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard_app', '0002_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.CharField(default='Normal', max_length=255),
            preserve_default=False,
        ),
    ]
